// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-wrap justify-center items-center content-evenly h-27 w-full border-b-2" >
          {/* <h1 className="text-4xl">Property Listings</h1> */}
          <Image src="/titlePhoto.jpeg" alt="" className="w-full" width={400} height={40}/>
        </div>
        {children}
      </body>
    </html>
  )
}
